### ISSUE TITLE
Information in README.md is confusing regarding versions

### ISSUE THREAD

**Issue by SevaSafris** [opentracing-contrib/java-spring-web#107]
The README.md says:

> Versions 1.x.y of the library are meant to target Spring Framework 5.x and Spring Boot 2.x while versions 0.x.y are meant to be used with Spring Framework 4.3 and Spring Boot 1.5.

What "versions" is this referring to? Is this referring to versions of this Instrumentation Plugin? Because there are no versions 1.x.y, but instead there are versions 2.x.y.

**Comment by geoand** [comment]
Good catch, thanks! When this was created, the latest version was 1.0.0. I will update it.
