### ISSUE TITLE
Spring MVC integration example

### ISSUE THREAD

**Issue by vbhumireddy** [opentracing-contrib/java-spring-web#118]
Dear Sir/Madam,
I am trying to integrate my Spring MVC applications with Opentracing and Jaeger/Zipkin. I didn;t find any examples or API that can support Spring MVC.

As given in documentation FilterRegistrationBean is a SpringBoot API class, But I want to try to integrate with Spring MVC.

Can you please help me. Appreciate your help in advance.

**Comment by pavolloffay** [comment]
This module contains integration tests with spring MVC https://github.com/opentracing-contrib/java-spring-web/tree/master/opentracing-spring-web-itest/mvc
