### ISSUE TITLE
Clarify project status

### ISSUE THREAD

**Issue by ttddyy** [opentracing-contrib/java-spring-web#123]
On the README, it says
> "Use opentracing-spring-cloud instead"

what does it really mean?

Is it indicating this project is inactive; so, don't use `java-spring-web` and move to `opentracing-spring-cloud`??

It is very confusing.

Appreciate clarifying the intention there.

**Comment by geoand** [comment]
Hi,

taken out of context I agree it's confusing. However if you read the description after that I think  you'll have a better understanding.

The project are both equally active, they just address different needs.

If you feel that this should be made more clear, we are of course open to suggestions

**Comment by ttddyy** [comment]
I think saying _"Use opentracing-spring-cloud instead"_ in title gives impression that the statement has concluded only by the title; thus people may think the title is saying - just to use `opentracing-spring-cloud` instead of `java-spring-web`.

I think it is better to state the difference between those two projects and gives user's choice that you may choose `opentracing-spring-cloud` if that is more suitable in user's use case.

May be making title like:

- `java-spring-web` or `opentracing-spring-cloud`
- comparison to `opentracing-spring-cloud`
- `java-spring-web` vs `opentracing-spring-cloud`


The first statement in the section:
> As it was mentioned above this library traces only inbound/outbound HTTP requests. 

Please put comma between _"above"_ and _"this library"_, which would I think highlight more on "above" section.
_"As it was mentioned above, this library ..."_

**Comment by geoand** [comment]
Thanks!

I'll update it soon
