### ISSUE TITLE
Version 0.3.4 fails with OpenTracing API 0.33.0

### ISSUE THREAD

**Issue by fabiomargarido** [opentracing-contrib/java-spring-web#128]
Is it possible to have [this commit](https://github.com/opentracing-contrib/java-spring-web/commit/696627213665174f3df5e4dbad405045066d54d0) (or at least the API bump part) integrated into the 0.3 branch? I'm stuck in an older Spring Boot version and right now 0.3.4 fails with the latest OpenTracing API because `startActive()` has been removed and not only deprecated.

Thanks.

**Comment by pavolloffay** [comment]
0.3 branch is using OpenTracing 0.31.0 https://github.com/opentracing-contrib/java-spring-web/blob/release-0.3.4/pom.xml. The commit you referencing is bumping OT API to 0.32.0.


versions 2.x.x are using older OT version. We do not plan to support matrix of OT versions and spring boot.

**Comment by geoand** [comment]
@fabiomargarido we don't plan to support that, but I should be easy for you to do a fork an cherry pick the necessary commits. 
I assume you would only keep your fork until you can move you service to a new version of Spring Boot

**Comment by fabiomargarido** [comment]
Ok, thanks for the response guys.
