### ISSUE TITLE
Span not finished when subscription is cancelled

### ISSUE THREAD

**Issue by NHebrard** [opentracing-contrib/java-spring-web#133]
Hello!

In the `TracingOperator` component is there any good reason the not finish the span when the wrapped source has been canceled?

I would change
```java
class TracingOperator extends MonoOperator<Void, Void> {
    
    @Override
    public void subscribe(final CoreSubscriber<? super Void> subscriber) {
        // ...
        try (final Scope scope = tracer.scopeManager().activate(span)) {
            exchange.getAttributes().put(TracingWebFilter.SERVER_SPAN_CONTEXT, span.context());
            source.subscribe(new TracingSubscriber(subscriber, exchange, context, span, spanDecorators));
        }
    }
```
To
```java
class TracingOperator extends MonoOperator<Void, Void> {
    
    @Override
    public void subscribe(final CoreSubscriber<? super Void> subscriber) {
        // ...
        try (final Scope scope = tracer.scopeManager().activate(span)) {
            exchange.getAttributes().put(TracingWebFilter.SERVER_SPAN_CONTEXT, span.context());
            source.doOnCancel(() -> span.finish())
               .subscribe(new TracingSubscriber(subscriber, exchange, context, span, spanDecorators));
        }
    }
```

Happy to contribute if needed!

Thanks.

**Comment by geoand** [comment]
Hi,

that seems reasonable to me

**Comment by NHebrard** [comment]
@geoand Would you mind triggering a release?

**Comment by geoand** [comment]
I actually want the dust to setttle regarding the previous release, so why don't you ping me again please towards the end of the week?

**Comment by NHebrard** [comment]
This bug fix is somehow important for my team as we would like to have a complete trace visualization in the Jaeger UI.
But, we can wait a few days more as the number of impacted spans is low.

Thanks!

**Comment by geoand** [comment]
Cool :)

**Comment by NHebrard** [comment]
Hello,
Sorry to bother you again. Can we plan a release if there is no issue on your side?

Thanks!

**Comment by NHebrard** [comment]
Thanks for the new release!
