### ISSUE TITLE
Improve skip pattern

### ISSUE THREAD

**Issue by pavolloffay** [opentracing-contrib/java-spring-web#40]
Skip pattern should include all static files and common health endpoints used in spring.

**Comment by jpkrohling** [comment]
Should we have a single pattern across all places that uses a skip pattern? In other words, should I change the Servlet repository to use the skip pattern you'll use here ?

**Comment by pavolloffay** [comment]
IIRC servlet instrumentation does not use any default value for skip pattern.

The default value in this repo will probably include spring specific patterns (e.g. spring actuator).
