### ISSUE TITLE
Should client interceptor use more information for generating operation name?

### ISSUE THREAD

**Issue by elgris** [opentracing-contrib/java-spring-web#47]
Currently client interceptor uses only [method of request as an operation name for new spans](https://github.com/opentracing-contrib/java-spring-web/blob/master/opentracing-spring-web/src/main/java/io/opentracing/contrib/spring/web/client/TracingRestTemplateInterceptor.java#L59):
```
ActiveSpan span = tracer.buildSpan(httpRequest.getMethod().toString())
                .withTag(Tags.SPAN_KIND.getKey(), Tags.SPAN_KIND_CLIENT).startActive();
```

Does it make sense to add a request path to `operation name`? Or maybe make an `operation name generator` to support customisation of that? Otherwise for many outgoing `GET` requests to different targets, spans appear with the same operation name `GET`.

**Comment by pavolloffay** [comment]
Span can be modified via decorators. Path should not be used as operation name due to cardinality problems.
