### ISSUE TITLE
Fails when using Spring Webflux

### ISSUE THREAD

**Issue by darrenhaken** [opentracing-contrib/java-spring-web#59]
Are you aware this fails with Spring Webflux?

**Comment by pavolloffay** [comment]
No, thanks for reporting. Do you have any error logs/reproducer? Would you like to submit a fix for it?

**Comment by darrenhaken** [comment]
I can take a look at submitting a fix sure, I’ll open a PR soon

**Comment by pavolloffay** [comment]
@darrenhaken thanks :+1:

**Comment by mdvorak** [comment]
I believe that `TracerAutoConfiguration` and `TracerRegisterAutoConfiguration` does not belong in this library (java-spring-web) at all. Then this jar can be for webflux app excluded completely (and possibly new designed for reactive stack should be created).

However, for easier -starter integration, it I suggest adding `@ConditionalOnClass`. Its easy change on its own, but adding tests will be more time consuming.

* Add `@ConditionalOnClass(Servlet.class)` to `ServerTracingAutoConfiguration`
* Add `@ConditionalOnClass(RestTemplate.class)` to `RestTemplateAutoConfiguration`
* Add `@ConditionalOnClass(AsyncRestTemplate.class)` to `AsyncRestTemplateAutoConfiguration`

Change is in commit f7fff3e35cbc397b1be90968e1d8441564afea02

**Comment by pavolloffay** [comment]
@mdvorak is this resolved by #68 ?

**Comment by mdvorak** [comment]
Only partially, I did add condition to new config class for client, but did not touch `ServerTracingAutoConfiguration`.
So, add `@ConditionalOnClass(Servlet.class)` and you're done.

**Comment by geoand** [comment]
Sorry for being late to the party but I see any indication that the module supports Spring 5 yet, much less Webflux which is a non-Servlet Web framework of it's own.

Am I missing something obvious here?

**Comment by mdvorak** [comment]
@geoand Of course, same can be achieved by `<exclusions>` when referenced by ot-spring-cloud. Still, does not do any harm either.

**Comment by pavolloffay** [comment]
I have created #72. Webflux support will need a separate instrumentation for both client and server side.
