### ISSUE TITLE
FilterRegistrationBean not defined in non spring boot application

### ISSUE THREAD

**Issue by abhsinh2** [opentracing-contrib/java-spring-web#71]
I have not spring mvc application NOT spring boot. In readme, example to extend WebMvcConfigurerAdapter shows use of FilterRegistrationBean which is spring boot class. What should I use for non spring boot application?

is below code fix the problem?
@Override
    public void addInterceptors(InterceptorRegistry registry) {
        registry.addInterceptor(new TracingHandlerInterceptor(tracer)).addPathPatterns("/*");
    }

**Comment by pavolloffay** [comment]
@abhsinh2 maybe you can use `ServletContextListener` to register the filter there

**Comment by pavolloffay** [comment]
Here is an example https://github.com/opentracing-contrib/java-spring-web/blob/master/opentracing-spring-web-itest/mvc/src/test/java/io/opentracing/contrib/spring/web/interceptor/itest/mvc/SpringMVCConfiguration.java

**Comment by pavolloffay** [comment]
@abhsinh2 I will close the issue. If you have more questions feel free to re-open/comment. 

The mvc configuration can be found in `opentracing-spring-web-itest/mvc` module
