### ISSUE TITLE
Rename opentracing-spring-web-autoconfigure to opentracing-spring-web-starter

### ISSUE THREAD

**Issue by cmoulliard** [opentracing-contrib/java-spring-web#75]
All the Spring Boot modules = starters containing the definition/list of the dependencies to be packaged like also the code to be used during bootstrap process and to configure the beans contains, part of their name, the word `starter`. 

I propose to rename this project from `opentracing-spring-web-autoconfigure` to `opentracing-spring-web-starter` to adopt/follow the same convention. Make sense @geoand @pavolloffay @objectiser ?

Same convention should also be followed for the `cloud` module -> `opentracing-spring-cloud-starter`

**Comment by pavolloffay** [comment]
+1 @geoand do you want to fix it?

**Comment by geoand** [comment]
@pavolloffay Sure thing

**Comment by whiskeysierra** [comment]
Just want to leave this here:

https://docs.spring.io/spring-boot/docs/current/reference/html/spring-boot-features.html#boot-features-custom-starter

Auto configurations and starters can be kept separate as well.
