### ISSUE TITLE
Upgrade to Spring Boot 2.1.1.RELEASE

### ISSUE THREAD

**Issue by gytis** [opentracing-contrib/java-spring-web#89]

**Comment by geoand** [comment]
@gytis Do you want to update this? It should just be a matter updating the maven properties since we already moved to SB 2.1.0 last week

**Comment by gytis** [comment]
Sure, will raise a PR.

**Comment by geoand** [comment]
Once we merge the PR I will do a release and then also update https://github.com/opentracing-contrib/java-spring-jaeger

**Comment by geoand** [comment]
Fixed via 094de67
