### ISSUE TITLE
[Question] Example / how to use SpanDecorator?

### ISSUE THREAD

**Issue by etsangsplk** [opentracing-contrib/java-spring-web#91]
It looks like use can supply their own span decorators with their tracer 👍 
https://github.com/opentracing-contrib/java-spring-web/blob/0933caece7de11ae9f9d411113a5473d35288cf8/opentracing-spring-web/src/main/java/io/opentracing/contrib/spring/web/interceptor/TracingHandlerInterceptor.java#L50
is there an example of how to do it and wire it up? It is not at all obvious how to do it. 
Only got to the point of 
```public class RequestSpanDecorator implements HandlerInterceptorSpanDecorator {
``` and override onPreHandle and onAfterCompletion. but then what.

**Comment by pavolloffay** [comment]
>  but then what.

What is not clear? Just implement the decorator interface [1] and supply it to `TracingHandlerInterceptor`. If you are using SB starter `opentracing-spring-web-starter` you can expose the decorator impl as a bean and instrumentation should pick it up.

[1]:  https://github.com/opentracing-contrib/java-spring-web/blob/master/opentracing-spring-web/src/main/java/io/opentracing/contrib/spring/web/interceptor/HandlerInterceptorSpanDecorator.java#L18

**Comment by pavolloffay** [comment]
I will close this, feel free to reopen if you run into any issues.
