### ISSUE TITLE
Deprecated usage of scopeManager.activate(..., false)

### ISSUE THREAD

**Issue by wcarmon** [opentracing-contrib/java-spring-web#92]
Your usage:
https://github.com/opentracing-contrib/java-spring-web/blob/f5a11436e98615fb7368e2b7acdad380e890cf8e/opentracing-spring-web/src/main/java/io/opentracing/contrib/spring/web/interceptor/TracingHandlerInterceptor.java#L83

See the source for 0.32.x:

https://github.com/opentracing/opentracing-java/blob/release-0.32.0-RC1/opentracing-api/src/main/java/io/opentracing/ScopeManager.java#L115

**Comment by larchanjo** [comment]
@wcarmon I don't understand why this is a issuer?

**Comment by pavolloffay** [comment]
This is not an issue, however we should migrate from a deprecated API anyways. I will close this. Feel free to comment if there are more questions.

**Comment by wcarmon** [comment]
@larchanjo It's only an issue for people that want to use the newest versions of the OpenTracting API.

If people are stuck on older versions, they won't notice.

@pavolloffay That's fine, I was pointing out where this lib might break in the future.  (Due to misalignment with the OpenTracing java api)

**Comment by denisw** [comment]
The deprecated `ScopeManager` methods have been remove from the OpenTracing v0.33 API. This has now thus become an issue because it prevents teams from upgrading Jaeger to v1.0.0, which implements the v0.33 API.

**Comment by geoand** [comment]
I do plan on working on the move to the latest OpenTracing  and Jaeger Client versions in the next few weeks.

**Comment by denisw** [comment]
Why is this closed? There are still uses of `ScopeManager#activate(Span, boolean)` in the codebase.

**Comment by pavolloffay** [comment]
It will be done in https://github.com/opentracing-contrib/java-spring-web/pull/116

**Comment by larchanjo** [comment]
Ok, thank you soo much!
