### ISSUE TITLE
No Service dependencies shown in Jaeger

### ISSUE THREAD

**Issue by derXear** [opentracing-contrib/java-spring-web#97]
Hello, 

i have a minimal example with 2 Spring Boot Apps where one calls the other. 
I can see all spans of the apps in the Jaeger UI, but no dependency between the apps. Shouldn't this already work by autoconfiguration?

Here is a [link](https://github.com/derXear/opentracing-spring-boot-jaeger-example) to the minimal example. If it's not a bug, maybe someone could push me into the right direction at Stackoverflow [here](https://stackoverflow.com/questions/55239593/service-dependencies-not-shown-in-jaeger-between-spring-boot-applications) :)

Thanks in advance

**Comment by pavolloffay** [comment]
Closing per https://github.com/opentracing-contrib/java-spring-jaeger/issues/42
