### ISSUE TITLE
Actuator endpoint skipped by default

### ISSUE THREAD

**Issue by matheusfm** [opentracing-contrib/java-spring-web#98]
The Spring Boot 2.x had changed the actuator base path to `/actuator` and is not being skipped by default.
https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.0-Migration-Guide#base-path

**Comment by geoand** [comment]
Thanks for reporting @matheusfm! The PR from @larchanjo should take care of it

**Comment by pavolloffay** [comment]
@geoand do you mean #99? As it is merged can be this closed?

**Comment by geoand** [comment]
Yup, my bad, forgot to close this.
